-- MySQL Script generated by MySQL Workbench
-- Wed Dec  2 14:20:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema groupomania
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema groupomania
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `groupomania` DEFAULT CHARACTER SET utf8 ;
USE `groupomania` ;

-- -----------------------------------------------------
-- Table `groupomania`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupomania`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`active` INT UNSIGNED NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `groupomania`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupomania`.`post` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userId` INT UNSIGNED NOT NULL,
  `titlePost` VARCHAR(45) NOT NULL,
  `content` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `KEY` () VISIBLE,
  INDEX `fk_Posts_users_id_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_Posts_users_id`
    FOREIGN KEY (`userId`)
    REFERENCES `groupomania`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupomania`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupomania`.`comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `postId` INT UNSIGNED NOT NULL,
  `userId` INT UNSIGNED NOT NULL,
  `content` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comments_posts_id_idx` (`postId` ASC) VISIBLE,
  INDEX `fk_Comments_users_id_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_Comments_posts_id`
    FOREIGN KEY (`postId`)
    REFERENCES `groupomania`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Comments_users_id`
    FOREIGN KEY (`userId`)
    REFERENCES `groupomania`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
